on: workflow_dispatch

env:
  BUILD_VERSION: 1.3.2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Clone Source Code
        run: |
          git clone -b equuleus --single-branch https://github.com/vyos/vyos-build.git vyos-build
          cd ./vyos-build/
          ./configure --architecture amd64 --build-type release --version $BUILD_VERSION
          mkdir -p artifacts
          
      - name: Build ISO Image
        id: iso
        working-directory: ./vyos-build
        run: |
          make iso && echo "status=success" >> $GITHUB_OUTPUT
          cp -f ./build/vyos-$BUILD_VERSION-amd64.iso ./artifacts
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vyos-${{ env.BUILD_VERSION }}-amd64-images
          path: vyos-build/artifacts
          
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: vyos-${{ env.BUILD_VERSION }}-amd64-images

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: VyOS v${{ env.BUILD_VERSION }} LTS Release
          body: VyOS v${{ env.BUILD_VERSION }} LTS Release
          draft: false
          prerelease: false
          tag_name: VyOS
          files: |
            vyos-${{ env.BUILD_VERSION }}-amd64.iso
